spring:
  application:
    name: Spring-Boot-Kafka-Batch-Sample
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx.
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        isolation.level: read_committed
    listener:
      type: batch

logging:
  level:
    root: info
    org.springframework.kafka.core: trace #kafka 로그
    org.springframework.transaction.interceptor: trace # 트랜잭션 로그
