global:
  # 스크립 주기
  scrape_interval: 5s
  # 규칙 평가 기준
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']