spring.application.name=SpringBoot4Demo

spring.devtools.trace.probability=1.0
management.observations.annotations.enabled=true
management.tracing.sampling.probability=1.0

#management.observations.key-values.region=kr-seoul
#management.observations.key-values.stack=dev
