server:
  port: 9000
spring:
  application:
    name: Spring-Keycloak-Sample
  docker:
    compose:
      file: ./Spring-Security/Spring-Keycloak-Sample/docker-compose.yml
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: down
        timeout: 10s
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: sample-service
            client-secret: sample-keycloak-secret
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:26343/realms/my-realm