services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
      - "61613:61613"  # STOMP
      - "15674:15674"  # Web-STOMP
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: [
      "bash", "-c",
      "chmod 400 /var/lib/rabbitmq/.erlang.cookie; 
      rabbitmq-plugins enable rabbitmq_management;
      rabbitmq-plugins enable rabbitmq_stomp
      rabbitmq-plugins enable rabbitmq_web_stomp;
      rabbitmq-server" ]
    restart: always
